### ISSUE TITLE
Weird error (not my description, NPM's)

### ISSUE THREAD

**Issue by stopsatgreen** [shama/voxel-drone#11]
Install and start this through NPM, all seems fine, but visiting localhost:8080 gives the error report below. The online demo works with no problems.

```
listening on http://localhost:8080/
200    7ms      707B /index.html

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)
npm ERR! weird error 8
npm ERR! not ok code 0
```

**Comment by judemin** [comment]
I just tried all of the solution that you have witten but i still get 
listening on http://localhost:8080/
200    7ms      707B /index.html

events.js:72
        throw er; // Unhandled 'error' event

this error.

At first i got the same error when i type
npm start
so i changed package.json's 28th code to
 "start": "cd example && ..\node_modules.\.bin\beefy world.js 8080 -- -d -r ar-drone-browserified:ar-drone"
so I opened server but whenever i go to http://localhost:8080 i get the error

i googled al lot and i changed code many times but i can't solve it

my npm version is 2.11.3
and node version is 0.12.7
and i'm using Win8 64-bit

![default](https://cloud.githubusercontent.com/assets/20484492/16893435/bcbd9400-4b72-11e6-9e4d-20e27aba5dc3.PNG)
