### ISSUE TITLE
Error when visiting localhost

### ISSUE THREAD

**Issue by craigxyz** [shama/voxel-drone#17]
Installs fine with npm but when visiting http://localhost:8080, the following error appears:

`~\voxel-drone\node_modules\response-stream\index.js:64
            if (src[name]) s[name] = src[name].bind(src);
                                               ^

TypeError: src[name].bind is not a function
    at \~\voxel-drone\node_modules\response-stream\index.js:64:48
    at Array.forEach (<anonymous>)
    at copyStream (\~\voxel-drone\node_modules\response-stream\index.js:63:10)
    at module.exports (\~\voxel-drone\node_modules\response-stream\index.js:6:18)
    at handle_static (\~\voxel-drone\node_modules\beefy\lib\server.js:144:14)
    at Server.beefy_server (\~\voxel-drone\node_modules\beefy\lib\server.js:74:16)
    at Server.emit (events.js:315:20)
    at Server.EventEmitter.emit (domain.js:485:12)
    at parserOnIncoming (_http_server.js:789:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)`

I've tried to run this on a few systems and the '.bind is not a function' error crops up regardless of platform.

**Comment by shama** [comment]
Sadly I'm not surprised this project doesn't work anymore. This project was made 8 years ago and last updated over 4 years ago. It's based on the old AR Drone which I don't think is sold anymore and an old version of voxel.js.

If you're trying to get the example working locally, I would double check your version of voxel-engine and voxel-player is the same used here: https://github.com/shama/voxel-drone/blob/master/package.json#L45

But it's using some really old dependencies that I have no idea what the state of them are anymore. Might be cool to turn this into another voxel based drone simulator but I don't have any plans to do that any time soon.
